name: CI
on: 
  push:
    branches:
      - redo

jobs:
  linter:
    name: golangci-lint
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - uses: golangci/golangci-lint-action@v2
  test:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: start docker containers
        run: make demo
      - name: migration
        run: make migrate
      - name: Run test
        run: make test